### ISSUE TITLE
customizable status format

### ISSUE THREAD

**Issue by aaashleyyyy** [OvalQuilter/lyrics-sender#1]
add a text box where you can set a specific format for how the lyrics are displayed on your status

example: "🎶 {timestamp} {songname} - {lyrics}🎶"

some extra tags you could add: {timestampnobrackets}, {songname}, {lyricslowercase}, {lyricsuppercase}, {songnameuppercase}, {songnamelowercase}, {songartist}, {songartistlowercase}, {songartistuppercase}

**Comment by OvalQuilter** [comment]
👋 Hello! Your request has been accepted and will be added in next update. Thanks for participating!
**P.S.** Sorry for the late answer, I have other project to work on, but don't worry I won't leave this one.
